/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DiceChess;

import view.SetupMenu;

public class App 
{

    public static void main(String[] args) 
    {
    	 SetupMenu menu = new SetupMenu();
    }
}
